### ISSUE TITLE
LastLogin has been populated with unverified account

### ISSUE THREAD

**Issue by Mikes82** [brockallen/BrockAllen.MembershipReboot#496] opened 2015-02-09 02:12 UTC
Hi,

I’ve been running some create user and verifying tests and came up with the following issue:
 
If the user attempts to log in without verifying their account with the correct username and password, their UserAccounts  "LastLogin" field will be populated with the time stamp. Which occurs even though they have not successfully logged in. (Being the account hasn't been verified yet)
This means later down the track when using IsNew() to verify the user account it will return false.

I can set allowLoginAfterAccountCreation="false" in web.config to prevent this from occurring and then reset the IsLoginAllowed = true at the verification stage as a work around, but i was wondering if there is a better way to handle this issue?

Thanks.

**Comment by brockallen** [comment] 2015-02-10 04:27
I tried to reproduce this and can't. Here's what I did:

```
[TestMethod]
        public void MyTestMethod()
        {
            configuration.AllowLoginAfterAccountCreation = true;
            
            var acct = subject.CreateAccount("test", "pass", "test@test.com");

            var result = subject.Authenticate("test", "badpass");
            Assert.IsFalse(result);

            acct = subject.GetByID(acct.ID);
            Assert.IsTrue(acct.IsNew());

        }
```
`IsNew` checks last login for `null`. 

So since I can't reproduce it, perhaps you can write a test to reproduce the problem you're seeing?

**Comment by girtsl** [comment] 2015-02-10 07:03
I'm experiencing the same issue. As usual, the devil is in the details - "If the user attempts to log in without verifying their account with the correct username and password".

If you change your test to use correct password for authentication, the test will fail.

**Comment by brockallen** [comment] 2015-02-10 15:01
Ah, ok -- missed that. I'll try again.

**Comment by brockallen** [comment] 2015-02-10 15:14
Ok, so yes, was now able to repro this -- looks like it was a bug due to a typo in `Authenticate`. Fixed on dev and will release updated NuGet soon.

**Closed** 2015-02-10 20:10 UTC
Labels: can't reproduce, question

**Comment by parkinsona** [comment] 2015-02-10 22:43
Hey Brock, 
Will IdentityServer.MembershipReboot be updated to include this update?

**Comment by brockallen** [comment] 2015-02-10 22:47
You should be able to manually update the nuget.
